### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by blockchainsg** [TradeTrust/tradetrust-website#156]
Hi

When I tried to run npm install for api-verify, i encounter error.  See attached error log.
Please advise.
[npm-debug.log](https://github.com/TradeTrust/tradetrust-website/files/4721891/npm-debug.log)

Regards
Mike

**Comment by yehjxraymond** [comment]
```
53685 error code EMISSINGARG
53686 error typeerror Error: Missing required argument #1
53686 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
53686 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
53686 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
53686 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
53686 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
53686 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
53686 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
53686 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
53686 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
53686 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
53687 error typeerror This is an error with npm itself. Please report this error at:
53687 error typeerror     <http://github.com/npm/npm/issues>
53688 verbose exit [ 1, true ]
```

Seemed like a problem with npm itself, you should check that.

Also you may add instructions for error to be reproduced such as the OS that you are running to see if we can reproduce the error. But from the look of this log it's not an error with the api-verify code.

**Comment by Nebulis** [comment]
maybe you should try to upgrade your npm version

```
53683 error node v8.10.0
53684 error npm  v3.5.2
```

**Comment by blockchainsg** [comment]
Thanks. After upgrade it is fine now.
